name: Publish Falco Rules

on:
  push:
    branches:
      - main
    paths:
      - 'rules/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  push_falco_rules:
    runs-on: ubuntu-latest
    env:
      OCI_REGISTRY: ghcr.io
      OCI_ARTIFACT_NAME: falco-rules
      OCI_ARTIFACT_VERSION: ${{ github.ref_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Push Falco rules as OCI artifact
        run: |
          set -ex 
          echo "${env.OCI_REGISTRY},${{ github.repository_owner }},${{ secrets.GITHUB_TOKEN }}" > env_file
          docker run --rm --env-file env_file -v $(pwd):/rules falcosecurity/falcoctl:0.11 \
          registry push \
          --config /dev/null \
          --type rulesfile \
          --version ${env.OCI_ARTIFACT_VERSION} \
          ${env.OCI_REGISTRY}/${GITHUB_REPOSITORY}:${env.OCI_ARTIFACT_VERSION} \
          /rules/rules/falco_rules.yaml


      - name: cleanup
        if: always()
        run: rm -f env_file
